PLAN_TEMPLATES = {
    "stabilization_7d": {
        "title": "7-Day Stabilization Plan",
        "days": 7,
        "focus": ["check-in", "breathing", "sleep routine", "small action"],
        "daily_steps": [
            "Day 1: Daily check-in (mood/anxiety/sleep/energy). Try 4-7-8 breathing once.",
            "Day 2: Check-in. Set a fixed bedtime window (±30 min). One small pleasant activity.",
            "Day 3: Check-in. 4-7-8 breathing morning and evening. 10-min walk.",
            "Day 4: Check-in. Review sleep quality. Write down one worry, set it aside.",
            "Day 5: Check-in. Practice body scan before bed. Contact one support person.",
            "Day 6: Check-in. Reflect on which step helped most this week. Repeat it.",
            "Day 7: Weekly review. Summarize mood/anxiety trends. Plan next week's focus.",
        ],
    },
    "anxiety_14d": {
        "title": "14-Day Anxiety Relief Plan",
        "days": 14,
        "focus": ["trigger tracking", "thought check", "breathing", "worry scheduling"],
        "daily_steps": [
            "Day 1: Daily check-in. Identify top 3 anxiety triggers this week.",
            "Day 2: Check-in. Practice thought record: situation → thought → evidence.",
            "Day 3: Check-in. Try worry scheduling: 15 min at fixed time, then stop.",
            "Day 4: Check-in. 4-7-8 breathing when anxiety spikes. Log intensity before/after.",
            "Day 5: Check-in. Review thought records. Spot one cognitive distortion.",
            "Day 6: Check-in. Behavioral experiment: approach one avoided situation.",
            "Day 7: Weekly review. Compare anxiety scores to last week.",
            "Day 8: Check-in. Add grounding technique (5-4-3-2-1 senses).",
            "Day 9: Check-in. Practice worry scheduling + thought record together.",
            "Day 10: Check-in. Identify one values-based action despite anxiety.",
            "Day 11: Check-in. Review cognitive distortions. Challenge the top one.",
            "Day 12: Check-in. Repeat behavioral experiment with a harder situation.",
            "Day 13: Check-in. Write a coping statement for your top trigger.",
            "Day 14: Final review. Summarize what worked. Plan maintenance steps.",
        ],
    },
    "sleep_14d": {
        "title": "14-Day Sleep Improvement Plan",
        "days": 14,
        "focus": ["sleep log", "wind-down", "stimulus control", "morning anchor"],
        "daily_steps": [
            "Day 1: Log bedtime, wake time, sleep quality. No screens 30 min before bed.",
            "Day 2: Sleep log. Create a 20-min wind-down routine (e.g., reading, stretching).",
            "Day 3: Sleep log. Fixed wake time (even on weekends). Morning sunlight exposure.",
            "Day 4: Sleep log. If awake >20 min, leave bed and return when sleepy.",
            "Day 5: Sleep log. No caffeine after 2 PM. Review sleep efficiency.",
            "Day 6: Sleep log. Add relaxation breathing to wind-down routine.",
            "Day 7: Weekly review. Compare sleep hours and quality to baseline.",
            "Day 8: Sleep log. Adjust wind-down start time if needed.",
            "Day 9: Sleep log. Practice stimulus control: bed = sleep only.",
            "Day 10: Sleep log. Morning anchor: fixed breakfast + 10-min walk.",
            "Day 11: Sleep log. Reduce nighttime worrying with worry journal at 6 PM.",
            "Day 12: Sleep log. Evaluate if naps help or hurt night sleep.",
            "Day 13: Sleep log. Fine-tune the routine that works best.",
            "Day 14: Final review. Summarize sleep improvements. Plan maintenance.",
        ],
    },
}
