PLAN_TEMPLATES = {
    "stabilization_7d": {
        "title": "7-Day Stabilization Plan",
        "title_zh": "7 日稳定计划",
        "days": 7,
        "focus": ["check-in", "breathing", "sleep routine", "small action"],
        "description": "A gentle week-long plan to establish stability through daily check-ins, breathing exercises, and sleep routine anchors.",
        "description_zh": "一个温和的一周计划，通过每日打卡、呼吸练习和睡眠节律锚定来建立稳定感。",
        "daily_steps": {
            "day_1": {
                "title": "Day 1: 建立基线",
                "title_en": "Day 1: Establish Baseline",
                "actions": [
                    "完成首次情绪打卡（mood / anxiety / sleep / energy）",
                    "今晚记录入睡时间和起床时间",
                    "尝试一次 4-7-8 呼吸（吸气 4 秒、屏息 7 秒、呼气 8 秒，重复 3 轮）",
                ],
                "reflection_prompt": "今天最难的是什么？哪怕是小事也没关系。",
                "estimated_minutes": 10,
            },
            "day_2": {
                "title": "Day 2: 觉察情绪节律",
                "title_en": "Day 2: Notice Emotional Rhythm",
                "actions": [
                    "完成情绪打卡",
                    "在一天中设 3 个提醒（早/中/晚），各暂停 30 秒感受情绪",
                    "记录今天情绪最高和最低的时刻",
                ],
                "reflection_prompt": "什么时刻你感到稍微平静了一些？",
                "estimated_minutes": 10,
            },
            "day_3": {
                "title": "Day 3: 呼吸练习巩固",
                "title_en": "Day 3: Breathing Practice Consolidation",
                "actions": [
                    "完成情绪打卡",
                    "做 2 组 4-7-8 呼吸（每组 5 轮）",
                    "在感到紧张时立即使用呼吸练习",
                ],
                "reflection_prompt": "呼吸练习前后，身体感受有什么不同？",
                "estimated_minutes": 15,
            },
            "day_4": {
                "title": "Day 4: 睡眠节律锚定",
                "title_en": "Day 4: Sleep Routine Anchoring",
                "actions": [
                    "完成情绪打卡",
                    "今晚设定固定的「放下手机」时间（比平时早 15 分钟）",
                    "做一件让睡前 30 分钟变舒适的事（热水、阅读、轻音乐）",
                ],
                "reflection_prompt": "今晚的入睡过程和之前有什么不同？",
                "estimated_minutes": 15,
            },
            "day_5": {
                "title": "Day 5: 小步行动",
                "title_en": "Day 5: Small Action",
                "actions": [
                    "完成情绪打卡",
                    "选一件你一直在回避的小事（5 分钟内可完成），今天完成它",
                    "完成后给自己一个肯定",
                ],
                "reflection_prompt": "完成后的感受和预期有什么不同？",
                "estimated_minutes": 15,
            },
            "day_6": {
                "title": "Day 6: 回顾与调整",
                "title_en": "Day 6: Review and Adjust",
                "actions": [
                    "完成情绪打卡",
                    "回顾本周打卡数据，找出心情最好的一天",
                    "复制那一天做了的事，今天再做一次",
                ],
                "reflection_prompt": "这一周你学到了什么关于自己的事？",
                "estimated_minutes": 20,
            },
            "day_7": {
                "title": "Day 7: 稳定感锚定",
                "title_en": "Day 7: Anchor Stability",
                "actions": [
                    "完成情绪打卡",
                    "写下本周 3 件让你感到稍微好一点的事（不论多小）",
                    "选择本周一个有效的练习，计划下周继续",
                ],
                "reflection_prompt": "如果下周只能保留一个习惯，你会选哪个？",
                "estimated_minutes": 15,
            },
        },
    },
    "anxiety_14d": {
        "title": "14-Day Anxiety Relief Plan",
        "title_zh": "14 日焦虑缓解计划",
        "days": 14,
        "focus": ["trigger tracking", "thought check", "breathing", "worry scheduling"],
        "description": "A two-week plan combining CBT thought records, trigger tracking, and scheduled worry time.",
        "description_zh": "两周计划，结合 CBT 想法记录、触发因素追踪和定时焦虑时间。",
        "daily_steps": {
            "day_1": {
                "title": "Day 1: 焦虑基线",
                "actions": ["完成情绪打卡", "记录今天焦虑出现的 3 个时刻", "每个时刻标注强度（1-10）"],
                "reflection_prompt": "焦虑最高峰出现在什么情境下？",
                "estimated_minutes": 10,
            },
            "day_2": {
                "title": "Day 2: 触发因素识别",
                "actions": ["完成情绪打卡", "回顾昨天的 3 个时刻，找出共同触发因素", "写下一句话描述你的焦虑触发模式"],
                "reflection_prompt": "这些触发因素有共同点吗？",
                "estimated_minutes": 15,
            },
            "day_3": {
                "title": "Day 3: 第一个想法记录",
                "actions": ["完成情绪打卡", "做一个 CBT 想法记录（情境→情绪→自动想法→认知歪曲→平衡想法）", "评估练习前后焦虑强度"],
                "reflection_prompt": "写下平衡想法后，焦虑有变化吗？",
                "estimated_minutes": 20,
            },
            "day_4": {
                "title": "Day 4: 4-7-8 呼吸练习",
                "actions": ["完成情绪打卡", "早中晚各做一组 4-7-8 呼吸（5 轮/组）", "在焦虑升高时立即使用"],
                "reflection_prompt": "哪一组呼吸让你感到最明显的平复？",
                "estimated_minutes": 15,
            },
            "day_5": {
                "title": "Day 5: 焦虑时间",
                "actions": ["完成情绪打卡", "设定每天 15 分钟「焦虑时间」（固定时段）", "把白天的焦虑念头推迟到这个时段处理"],
                "reflection_prompt": "把焦虑推迟到固定时间，感觉如何？",
                "estimated_minutes": 15,
            },
            "day_6": {
                "title": "Day 6: 第二个想法记录",
                "actions": ["完成情绪打卡", "做第二个 CBT 想法记录", "对比第一次，有没有更容易找到平衡想法？"],
                "reflection_prompt": "练习想法记录后，你对自己的思维模式有什么新发现？",
                "estimated_minutes": 20,
            },
            "day_7": {
                "title": "Day 7: 第一周回顾",
                "actions": ["完成情绪打卡", "回顾本周打卡数据，对比焦虑趋势", "选择本周最有效的一个工具，下周加强"],
                "reflection_prompt": "这周哪个练习对你最有帮助？",
                "estimated_minutes": 20,
            },
            "day_8": {
                "title": "Day 8: 身体扫描",
                "actions": ["完成情绪打卡", "做一次 10 分钟身体扫描（从脚到头，逐部位觉察）", "记录身体最紧张的部位"],
                "reflection_prompt": "你的身体在哪里储存了焦虑？",
                "estimated_minutes": 15,
            },
            "day_9": {
                "title": "Day 9: 行为实验",
                "actions": ["完成情绪打卡", "选择一个你常回避的情境，今天主动进入 5 分钟", "记录实际感受 vs 预期感受"],
                "reflection_prompt": "实际情况和你担心的一样吗？",
                "estimated_minutes": 15,
            },
            "day_10": {
                "title": "Day 10: 第三个想法记录",
                "actions": ["完成情绪打卡", "做第三个 CBT 想法记录", "尝试识别 2 种以上认知歪曲"],
                "reflection_prompt": "你能更快地识别认知歪曲了吗？",
                "estimated_minutes": 20,
            },
            "day_11": {
                "title": "Day 11: 渐进式肌肉放松",
                "actions": ["完成情绪打卡", "做一次渐进式肌肉放松（每组肌肉绷紧 5 秒→放松 10 秒）", "重点放松昨天发现最紧张的部位"],
                "reflection_prompt": "放松后身体感受有什么变化？",
                "estimated_minutes": 20,
            },
            "day_12": {
                "title": "Day 12: 焦虑时间优化",
                "actions": ["完成情绪打卡", "把焦虑时间缩短到 10 分钟", "尝试在焦虑时间外用呼吸练习快速平复"],
                "reflection_prompt": "焦虑时间变短后，效果有变化吗？",
                "estimated_minutes": 15,
            },
            "day_13": {
                "title": "Day 13: 价值观澄清",
                "actions": ["完成情绪打卡", "写下 3 件对你真正重要的事", "为每件重要事做一个小行动"],
                "reflection_prompt": "当焦虑和价值观冲突时，你会选择什么？",
                "estimated_minutes": 20,
            },
            "day_14": {
                "title": "Day 14: 总结与计划",
                "actions": ["完成情绪打卡", "回顾两周打卡数据，对比焦虑趋势", "写下下个月要继续的 2 个练习"],
                "reflection_prompt": "两周下来，你对焦虑有了什么新的理解？",
                "estimated_minutes": 25,
            },
        },
    },
    "sleep_14d": {
        "title": "14-Day Sleep Improvement Plan",
        "title_zh": "14 日睡眠改善计划",
        "days": 14,
        "focus": ["sleep log", "wind-down", "stimulus control", "morning anchor"],
        "description": "A two-week plan based on CBT-I principles: sleep logs, wind-down routines, and stimulus control.",
        "description_zh": "基于 CBT-I 原则的两周计划：睡眠日志、睡前缓冲、刺激控制。",
        "daily_steps": {
            "day_1": {
                "title": "Day 1: 睡眠基线",
                "actions": ["完成情绪打卡", "记录昨晚的入睡时间、醒来时间、总睡眠时长", "评估今晨的精力（1-10）"],
                "reflection_prompt": "你的睡眠模式和理想状态差多远？",
                "estimated_minutes": 10,
            },
            "day_2": {
                "title": "Day 2: 睡前缓冲区",
                "actions": ["完成情绪打卡", "今晚设定睡前 30 分钟「缓冲区」", "缓冲区内：无屏幕、低光、安静活动"],
                "reflection_prompt": "缓冲区让你感到更困了吗？",
                "estimated_minutes": 10,
            },
            "day_3": {
                "title": "Day 3: 固定起床时间",
                "actions": ["完成情绪打卡", "设定固定起床时间（无论昨晚睡了多久）", "今晨准时起床，不赖床"],
                "reflection_prompt": "固定起床后，白天精力如何？",
                "estimated_minutes": 10,
            },
            "day_4": {
                "title": "Day 4: 床=睡眠",
                "actions": ["完成情绪打卡", "今天不在床上做非睡眠活动（看手机、工作等）", "只在困了才上床"],
                "reflection_prompt": "把床和睡眠关联起来，感觉如何？",
                "estimated_minutes": 10,
            },
            "day_5": {
                "title": "Day 5: 20 分钟规则",
                "actions": ["完成情绪打卡", "如果躺下 20 分钟还没睡着，起身离开卧室", "做一件安静的事，困了再回床"],
                "reflection_prompt": "起身离开让你感觉更好还是更焦虑？",
                "estimated_minutes": 10,
            },
            "day_6": {
                "title": "Day 6: 白天光照",
                "actions": ["完成情绪打卡", "今晨出门 15 分钟接受自然光", "白天保持室内光线充足"],
                "reflection_prompt": "白天光照后，晚上的困意来得更早了吗？",
                "estimated_minutes": 15,
            },
            "day_7": {
                "title": "Day 7: 第一周回顾",
                "actions": ["完成情绪打卡", "对比本周睡眠时长趋势", "选择本周最有效的一个改变，下周继续"],
                "reflection_prompt": "哪个改变对你的睡眠帮助最大？",
                "estimated_minutes": 15,
            },
            "day_8": {
                "title": "Day 8: 缩短卧床时间",
                "actions": ["完成情绪打卡", "今晚比平时晚 15 分钟上床", "保持固定起床时间"],
                "reflection_prompt": "缩短卧床时间后，入睡是否更快了？",
                "estimated_minutes": 10,
            },
            "day_9": {
                "title": "Day 9: 咖啡因截止",
                "actions": ["完成情绪打卡", "今天下午 2 点后不摄入咖啡因", "记录今晚的入睡难度"],
                "reflection_prompt": "减少咖啡因后，睡眠质量有变化吗？",
                "estimated_minutes": 5,
            },
            "day_10": {
                "title": "Day 10: 放松呼吸",
                "actions": ["完成情绪打卡", "在睡前缓冲区加入 4-7-8 呼吸（3 轮）", "记录练习后入睡时间"],
                "reflection_prompt": "呼吸练习后，入睡更快了吗？",
                "estimated_minutes": 15,
            },
            "day_11": {
                "title": "Day 11: 日间小憩管理",
                "actions": ["完成情绪打卡", "如果需要小憩，限制在 20 分钟以内", "小憩在下午 3 点前完成"],
                "reflection_prompt": "控制小憩后，夜间睡眠有改善吗？",
                "estimated_minutes": 10,
            },
            "day_12": {
                "title": "Day 12: 睡眠环境优化",
                "actions": ["完成情绪打卡", "检查卧室温度（理想 18-20°C）", "确保卧室黑暗、安静"],
                "reflection_prompt": "优化环境后，夜间醒来次数有变化吗？",
                "estimated_minutes": 15,
            },
            "day_13": {
                "title": "Day 13: 渐进延长",
                "actions": ["完成情绪打卡", "如果本周睡眠改善稳定，今晚早 5 分钟上床", "继续保持固定起床时间"],
                "reflection_prompt": "逐步延长睡眠时间的感觉如何？",
                "estimated_minutes": 10,
            },
            "day_14": {
                "title": "Day 14: 总结与维持",
                "actions": ["完成情绪打卡", "对比两周前后睡眠时长", "写下下个月要维持的 2 个习惯"],
                "reflection_prompt": "两周下来，你的睡眠观念有什么变化？",
                "estimated_minutes": 20,
            },
        },
    },
}
